//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// ATOTSSimulatortab.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_ATOTS_SIMULATORTAB_DIALOG   102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DLG_TAB1                    130
#define IDD_DLG_TAB2                    131
#define IDD_DLG_SEND_2                  136
#define IDD_DLG_SEND1                   137
#define IDD_DLG_SEND_1                  137
#define IDD_DLG_SEND2                   138
#define IDD_DLG_SEND_3                  138
#define IDD_DLG_SEND3                   139
#define IDD_DLG_SEND_4                  139
#define IDD_DLG_SEND4                   140
#define IDD_DLG_SEND_5                  140
#define IDD_DLG_SEND5                   141
#define IDD_DLG_SEND_6                  141
#define IDD_DLG_SEND_7                  142
#define IDD_DLG_SEND_8                  143
#define IDD_DLG_SEND_9                  144
#define IDD_DLG_SEND_10                 145
#define IDB_DISCONNECT                  146
#define IDD_DLG_SEND_11                 146
#define IDD_DLG_SEND_12                 147
#define IDB_CONNECT                     157
#define IDB_WARN                        160
#define IDB_BITMAP2                     161
#define IDB_CHECK                       161
#define IDB_BITMAP1                     163
#define IDR_MENU1                       165
#define IDB_ATO_NP                      166
#define IDB_ATO_AV                      167
#define IDB_ATO_CO                      168
#define IDB_ATO_DE                      169
#define IDB_ATO_FA                      170
#define IDB_ATO_NA                      171
#define IDB_ATO_RE                      172
#define IDB_BITMAP9                     173
#define IDB_BLANK                       173
#define IDC_TAB                         1000
#define IDC_ONOFF_PIC                   1001
#define IDC_MFCPROPERTYGRID1            1002
#define IDC_MPG_SEND                    1002
#define IDC_MPG_RECV                    1002
#define IDC_PLIST_COMBO                 1003
#define IDC_BTN_SEND                    1004
#define IDC_LIST_126                    1005
#define IDC_BTN_LOAD                    1005
#define IDC_LIST_MSG                    1006
#define IDC_BTN_SEND3                   1006
#define IDC_BTN_SEND_DYNAMIC            1006
#define IDC_BTN_SEND2                   1006
#define IDC_CHECK_AUTO                  1007
#define IDC_BTN_REJECT                  1008
#define IDC_LIST_CONNECT                1009
#define IDC_TS_ID                       1010
#define IDC_TS_PORT                     1011
#define IDC_BTN_SAVE                    1012
#define IDC_IP_TS                       1013
#define IDC_BTN_INIT                    1014
#define IDC_BTN_APPLY                   1015
#define IDB_ATO_EG                      1015
#define IDC_CHECK2                      1016
#define IDC_CHECK_MANUAL                1016
#define IDC_LIST_DEBUG                  1016
#define IDB_ATO_AV1                     1016
#define IDC_TAB_TS                      1017
#define IDB_ATO_CO1                     1017
#define IDB_ATO_DE1                     1018
#define IDC_COMBO1                      1019
#define IDC_CMB_RECV                    1019
#define IDB_ATO_EG1                     1019
#define IDC_BUTTON1                     1020
#define IDC_BUTTON_START                1020
#define IDB_ATO_FA1                     1020
#define IDC_CHECK1                      1021
#define IDC_CHB_AUTO                    1021
#define IDC_CHK_AUTOSA                  1021
#define IDC_CHK_AUTO_SA                 1021
#define IDB_ATO_NA1                     1021
#define IDC_BUTTON3                     1021
#define IDC_BTN_FINISH                  1021
#define IDC_BUTTON2                     1022
#define IDC_CMB_PACKET                  1022
#define IDC_BUTTON_CON                  1022
#define IDB_ATO_NP1                     1022
#define IDC_BTN_START                   1022
#define IDC_ETCS_ID                     1023
#define IDB_ATO_RE1                     1023
#define IDC_BUTTON_END                  1024
#define IDC_BUTTON_FINISH               1024
#define IDB_BLANK1                      1024
#define IDC_ATO_STATE                   1025
#define IDB_CHECK1                      1025
#define IDC_TRAIN                       1026
#define IDB_CONNECT1                    1026
#define IDC_CHK_SHOW_ALIVE              1026
#define IDC_SACON                       1027
#define IDC_HS                          1028
#define IDB_DISCONNECT1                 1028
#define IDC_ST                          1029
#define IDB_WARN1                       1029
#define IDC_HO                          1030
#define IDC_PIC_SA                      1031
#define IDC_PIC_HS                      1032
#define IDC_CMB_PACKET2                 1032
#define IDC_PIC_ST                      1033
#define IDC_PIC_HO                      1034
#define IDC_DRIVER                      1035
#define IDC_DASHBOARD                   1036
#define IDC_EDIT1                       1037
#define IDC_EDIT_LOG                    1037
#define IDC_LENGTH                      1038
#define IDC_EDIT3                       1038
#define IDC_cEN                         1038
#define IDC_EDIT2                       1039
#define IDC_EDIT4                       1039
#define IDC_cOP                         1039
#define IDC_LIST1                       1040
#define IDC_LB_DEBUG                    1040
#define IDC_BUTTON_DISCON               1040
#define IDC_cMAV                        1041
#define IDC_OB_PORT                     1042
#define IDC_IP_OB                       1043
#define IDC_ALIVE_COUNTER               1044
#define IDC_LIST2                       1045
#define IDC_STR_LIST                    1045
#define IDC_LOG_PAUSE                   1046
#define IDC_STATIC_1                    1047
#define IDC_STATIC_2                    1048
#define IDC_STATIC_3                    1049
#define IDC_STATIC_4                    1050
#define IDC_STATIC_5                    1051
#define IDC_RECV_ALIVE_COUNTER          1052
#define IDC_OP                          1053
#define IDC_EN                          1054
#define IDC_MAV                         1055
#define IDC_SALIVE_COUNTER              1056
#define IDC_BUTTON_ADD                  1057
#define IDC_BUTTON_ADD2                 1058
#define IDC_BUTTON_CLEAR                1058
#define IDC_CHECK3                      1061
#define IDC_CHECK_INDI                  1061
#define ID_32771                        32771
#define ID_32772                        32772
#define IDR_MENU_EXPAND                 32773
#define IDR_MENU_ALL                    32774
#define IDR_MENU_ALL_DELETE             32775
#define ID_32776                        32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
